#!/usr/bin/env bash
#
# Alethfeld Installation Script
#
# Builds the uberjar and installs the `af` command.
#
# Usage:
#   ./install.sh              # Install to ~/.local/bin (default)
#   ./install.sh /usr/local   # Install to /usr/local/bin
#
# Requirements:
#   - Java 11+ (java command available)
#   - Clojure CLI tools (clj command available)

set -euo pipefail

# Configuration
VERSION="0.2.1"
JAR_NAME="alethfeld-${VERSION}.jar"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default install prefix
PREFIX="${1:-$HOME/.local}"
BIN_DIR="${PREFIX}/bin"
LIB_DIR="${PREFIX}/lib/alethfeld"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Check requirements
check_requirements() {
    info "Checking requirements..."

    if ! command -v java &> /dev/null; then
        error "Java not found. Please install Java 11 or higher."
        exit 1
    fi

    JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
    if [[ "$JAVA_VERSION" -lt 11 ]]; then
        error "Java 11+ required. Found Java $JAVA_VERSION."
        exit 1
    fi
    info "Found Java $JAVA_VERSION"

    if ! command -v clj &> /dev/null; then
        error "Clojure CLI tools not found. Please install: https://clojure.org/guides/install_clojure"
        exit 1
    fi
    info "Found Clojure CLI tools"
}

# Build the uberjar
build_jar() {
    info "Building uberjar..."
    cd "$SCRIPT_DIR"

    clj -T:build uber

    if [[ ! -f "target/${JAR_NAME}" ]]; then
        error "Build failed - jar not found"
        exit 1
    fi

    info "Built target/${JAR_NAME}"
}

# Install the jar and wrapper script
install_files() {
    info "Installing to ${PREFIX}..."

    # Create directories
    mkdir -p "${BIN_DIR}"
    mkdir -p "${LIB_DIR}"

    # Copy jar
    cp "${SCRIPT_DIR}/target/${JAR_NAME}" "${LIB_DIR}/"
    info "Installed ${LIB_DIR}/${JAR_NAME}"

    # Create wrapper script
    cat > "${BIN_DIR}/af" << EOF
#!/usr/bin/env bash
# Alethfeld CLI wrapper
# Generated by install.sh

exec java -jar "${LIB_DIR}/${JAR_NAME}" "\$@"
EOF
    chmod +x "${BIN_DIR}/af"
    info "Installed ${BIN_DIR}/af"
}

# Verify installation
verify_install() {
    info "Verifying installation..."

    if [[ ! -x "${BIN_DIR}/af" ]]; then
        error "Wrapper script not executable"
        exit 1
    fi

    # Test the installation
    VERSION_OUTPUT=$("${BIN_DIR}/af" --version 2>&1)
    if [[ "$VERSION_OUTPUT" == *"Alethfeld"* ]]; then
        info "Verification passed: $VERSION_OUTPUT"
    else
        error "Verification failed"
        exit 1
    fi
}

# Print post-install instructions
print_instructions() {
    echo ""
    info "Installation complete!"
    echo ""
    echo "To use Alethfeld, ensure ${BIN_DIR} is in your PATH:"
    echo ""

    if [[ "$PREFIX" == "$HOME/.local" ]]; then
        echo "  # Add to your ~/.bashrc or ~/.zshrc:"
        echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    else
        echo "  # ${BIN_DIR} should already be in your PATH"
    fi

    echo ""
    echo "Then run:"
    echo "  af --help          # Show available commands"
    echo "  af init            # Initialize a new project"
    echo ""
}

# Main
main() {
    echo "Alethfeld Installer"
    echo "==================="
    echo ""

    check_requirements
    build_jar
    install_files
    verify_install
    print_instructions
}

main
