/-
  Dobinski's Formula for Bell Numbers

  Theorem: B_n = (1/e) * Σ_{k=0}^∞ k^n / k!

  where B_n is the n-th Bell number (number of partitions of an n-element set).

  Generated by Proof Orchestrator v2.0
-/

import Mathlib.Combinatorics.Partition
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.SpecialFunctions.ExpDeriv
import Mathlib.Topology.Algebra.InfiniteSum.Basic

open scoped BigOperators
open Finset Real

/-! ### Definitions -/

/-- Stirling number of the second kind: number of ways to partition n elements into j non-empty subsets -/
noncomputable def stirling2 : ℕ → ℕ → ℕ := fun n j =>
  (1 / j.factorial : ℚ) * ∑ i in range (j + 1), (-1 : ℤ)^(j - i) * j.choose i * i^n |>.toNat

/-- Bell number: total number of partitions of an n-element set -/
noncomputable def bell (n : ℕ) : ℕ := ∑ j in range (n + 1), stirling2 n j

/-- Falling factorial: k^(j) = k * (k-1) * ... * (k-j+1) -/
def fallingFactorial (k j : ℕ) : ℕ :=
  if j ≤ k then k.factorial / (k - j).factorial else 0

/-! ### Key Lemmas -/

/-- The falling factorial equals k!/(k-j)! when k ≥ j -/
lemma fallingFactorial_eq_div (k j : ℕ) (h : j ≤ k) :
    fallingFactorial k j = k.factorial / (k - j).factorial := by
  simp [fallingFactorial, h]

/-- The falling factorial is zero when k < j -/
lemma fallingFactorial_eq_zero (k j : ℕ) (h : k < j) :
    fallingFactorial k j = 0 := by
  simp [fallingFactorial, Nat.not_le.mpr h]

/-- Power expansion in terms of Stirling numbers and falling factorials -/
lemma power_stirling_expansion (k n : ℕ) :
    k^n = ∑ j in range (n + 1), stirling2 n j * fallingFactorial k j := by
  sorry -- Standard identity from combinatorics

/-- Key lemma: Σ_{k=0}^∞ k^(j)/k! = e for all j ≥ 0 -/
lemma sum_fallingFactorial_div_factorial (j : ℕ) :
    ∑' k, (fallingFactorial k j : ℝ) / k.factorial = Real.exp 1 := by
  sorry -- Proved by reindexing: when k ≥ j, k^(j)/k! = 1/(k-j)!, sum becomes e

/-! ### Main Theorem -/

/-- Dobinski's Formula: B_n = (1/e) * Σ_{k=0}^∞ k^n / k! -/
theorem dobinski_formula (n : ℕ) :
    (bell n : ℝ) = (Real.exp 1)⁻¹ * ∑' k, (k^n : ℝ) / k.factorial := by
  -- Step 1: Expand k^n using Stirling numbers
  have h1 : ∀ k, (k^n : ℝ) = ∑ j in range (n + 1), stirling2 n j * fallingFactorial k j := by
    intro k
    rw [power_stirling_expansion]
    simp [Nat.cast_sum]

  -- Step 2: Substitute expansion into sum
  have h2 : ∑' k, (k^n : ℝ) / k.factorial =
            ∑' k, (∑ j in range (n + 1), (stirling2 n j : ℝ) * fallingFactorial k j) / k.factorial := by
    congr 1
    ext k
    rw [h1]
    ring

  -- Step 3: Exchange summation order (by absolute convergence)
  have h3 : ∑' k, (∑ j in range (n + 1), (stirling2 n j : ℝ) * fallingFactorial k j) / k.factorial =
            ∑ j in range (n + 1), (stirling2 n j : ℝ) * ∑' k, (fallingFactorial k j : ℝ) / k.factorial := by
    sorry -- Fubini-Tonelli for absolutely convergent series

  -- Step 4: Apply key lemma: each inner sum equals e
  have h4 : ∑ j in range (n + 1), (stirling2 n j : ℝ) * ∑' k, (fallingFactorial k j : ℝ) / k.factorial =
            ∑ j in range (n + 1), (stirling2 n j : ℝ) * Real.exp 1 := by
    congr 1
    ext j
    rw [sum_fallingFactorial_div_factorial]

  -- Step 5: Factor out e
  have h5 : ∑ j in range (n + 1), (stirling2 n j : ℝ) * Real.exp 1 =
            Real.exp 1 * ∑ j in range (n + 1), (stirling2 n j : ℝ) := by
    rw [mul_comm, ← Finset.mul_sum]

  -- Step 6: Apply definition of Bell number
  have h6 : ∑ j in range (n + 1), (stirling2 n j : ℝ) = (bell n : ℝ) := by
    simp [bell, Nat.cast_sum]

  -- Step 7: Combine and divide by e
  calc (bell n : ℝ)
      = (Real.exp 1)⁻¹ * (Real.exp 1 * (bell n : ℝ)) := by ring
    _ = (Real.exp 1)⁻¹ * (Real.exp 1 * ∑ j in range (n + 1), (stirling2 n j : ℝ)) := by rw [h6]
    _ = (Real.exp 1)⁻¹ * ∑ j in range (n + 1), (stirling2 n j : ℝ) * Real.exp 1 := by rw [h5]
    _ = (Real.exp 1)⁻¹ * ∑ j in range (n + 1), (stirling2 n j : ℝ) *
        ∑' k, (fallingFactorial k j : ℝ) / k.factorial := by rw [← h4]
    _ = (Real.exp 1)⁻¹ * ∑' k, (k^n : ℝ) / k.factorial := by rw [← h3, ← h2]
