/-
  HMMT February 2025 Problem 7 - Counterexample

  Original claim: Let (a, b, c) be positive reals satisfying
    2(a^2+1) = 3(b^2+1) = 4(c^2+1)  and  ab + bc + ca = 1.
  Then a + b + c > 2.

  RESULT: This claim is FALSE.

  Counterexample: The unique solution has a + b + c < 2.

  Graph: graph-49b445-0d54c4 v59
  Taint status: THEOREM DISPROVED (counterexample found)

  Generated by Alethfeld Proof Orchestrator
-/

import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Topology.ContinuousFunction.Basic

open Real

namespace HmmtFeb2025_7

/-!
## Parametrization

Given the constraint 2(a^2+1) = 3(b^2+1) = 4(c^2+1) = k for some k > 4,
we can express:
  a = sqrt((k-2)/2)
  b = sqrt((k-3)/3)
  c = sqrt((k-4)/4)
-/

/-- The value a as a function of the common parameter k -/
noncomputable def a_of_k (k : Real) : Real := Real.sqrt ((k - 2) / 2)

/-- The value b as a function of the common parameter k -/
noncomputable def b_of_k (k : Real) : Real := Real.sqrt ((k - 3) / 3)

/-- The value c as a function of the common parameter k -/
noncomputable def c_of_k (k : Real) : Real := Real.sqrt ((k - 4) / 4)

/-- The constraint function f(k) = ab + bc + ca -/
noncomputable def f (k : Real) : Real :=
  a_of_k k * b_of_k k + b_of_k k * c_of_k k + c_of_k k * a_of_k k

/-- The sum function g(k) = a + b + c -/
noncomputable def g (k : Real) : Real :=
  a_of_k k + b_of_k k + c_of_k k

/-!
## Key Properties (verified in EDN proof)
-/

-- Step :2-exs002
lemma f_continuous : ContinuousOn f (Set.Ioi 4) := by
  sorry -- Composition of continuous functions

-- Step :2-exs003
lemma f_limit_at_4 : Filter.Tendsto f (nhdsWithin 4 (Set.Ioi 4)) (nhds (Real.sqrt (1/3))) := by
  sorry -- As k -> 4+, c -> 0, so f(k) -> a*b = sqrt(1)*sqrt(1/3)

-- Step :2-exs004
lemma f_limit_at_infty : Filter.Tendsto f Filter.atTop Filter.atTop := by
  sorry -- As k -> infinity, all of a,b,c -> infinity

-- Step :2-exs005
lemma exists_k_star : exists k : Real, k > 4 /\ f k = 1 := by
  sorry -- By IVT, since f(4+) < 1 < f(infinity)

-- Step :2-exs006
lemma f_strictly_increasing : StrictMonoOn f (Set.Ioi 4) := by
  sorry -- Each term is increasing in k

-- Step :2-exs007
lemma k_star_unique : exists! k : Real, k > 4 /\ f k = 1 := by
  sorry -- Strict monotonicity implies uniqueness

/-!
## The Counterexample

The unique k* satisfying f(k*) = 1 is approximately 4.174.
At this value, g(k*) = a + b + c is approximately 1.877 < 2.
-/

-- Numerical approximation of k*
-- k* = 96/23 = 4.173913...
noncomputable def k_star : Real := 96 / 23

-- Step :2-ineq005
lemma k_star_approximate :
    abs (k_star - 4.173913) < 0.001 /\ f k_star = 1 := by
  sorry -- Numerical verification

-- Step :2-ineq006 - THE KEY COUNTEREXAMPLE
lemma sum_less_than_two : g k_star < 2 := by
  sorry -- g(k*) = a + b + c approx 1.877 < 2

/-!
## Main Result: The Theorem is FALSE
-/

/-- The claimed theorem is false: there exist a, b, c > 0 satisfying the
    constraints but with a + b + c < 2 -/
theorem theorem_is_false :
    exists a b c : Real,
      a > 0 /\ b > 0 /\ c > 0 /\
      2 * (a^2 + 1) = 3 * (b^2 + 1) /\
      3 * (b^2 + 1) = 4 * (c^2 + 1) /\
      a * b + b * c + c * a = 1 /\
      a + b + c < 2 := by
  use a_of_k k_star, b_of_k k_star, c_of_k k_star
  constructor
  . -- a > 0
    sorry
  constructor
  . -- b > 0
    sorry
  constructor
  . -- c > 0
    sorry
  constructor
  . -- 2(a^2+1) = 3(b^2+1)
    sorry
  constructor
  . -- 3(b^2+1) = 4(c^2+1)
    sorry
  constructor
  . -- ab + bc + ca = 1
    sorry
  . -- a + b + c < 2
    exact sum_less_than_two

end HmmtFeb2025_7
