/-
  Determinant of a Rank-One Perturbation of a Diagonal Matrix

  Proposition: For a_1, a_2, ..., a_n ≠ 0,
  det(A) = (1 + Σ 1/a_k) · a_1 · a_2 · ... · a_n
  where A_ij = 1 + a_i · δ_ij

  Generated by Proof Orchestrator v2.0
-/

import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.Data.Matrix.Basic
import Mathlib.Algebra.BigOperators.Group.Finset

open scoped BigOperators Matrix
open Finset Matrix

variable {n : ℕ} [NeZero n]

/-- The ones vector -/
def onesVec (n : ℕ) : Fin n → ℝ := fun _ => 1

/-- The all-ones matrix (outer product of ones vector) -/
def onesMatrix (n : ℕ) : Matrix (Fin n) (Fin n) ℝ := fun _ _ => 1

/-- Diagonal matrix from a function -/
def diagMatrix (a : Fin n → ℝ) : Matrix (Fin n) (Fin n) ℝ := Matrix.diagonal a

/-! ### Matrix Determinant Lemma -/

/-- Matrix Determinant Lemma: det(M + uv^T) = (1 + v^T M^{-1} u) det(M)

Reference: Horn, R.A. and Johnson, C.R., Matrix Analysis, 2nd ed.,
Cambridge University Press, 2012, Section 0.8.5, Equation (0.8.5.11).
DOI: 10.1017/CBO9781139020411
-/
theorem matrix_det_lemma {n : ℕ} [DecidableEq (Fin n)] [Fintype (Fin n)]
    (M : Matrix (Fin n) (Fin n) ℝ) (u v : Fin n → ℝ) (hM : M.det ≠ 0) :
    (M + Matrix.col (Fin 1) u * Matrix.row (Fin 1) v).det =
    (1 + Matrix.dotProduct v (M⁻¹.mulVec u)) * M.det := by
  sorry -- See Horn & Johnson, Matrix Analysis (2012), Eq. (0.8.5.11)

/-! ### Main Proposition -/

/-- The matrix A with entries A_ij = 1 + a_i · δ_ij -/
def matrixA (a : Fin n → ℝ) : Matrix (Fin n) (Fin n) ℝ :=
  diagMatrix a + onesMatrix n

/-- Diagonal matrices are invertible when all entries are nonzero -/
lemma diag_invertible (a : Fin n → ℝ) (ha : ∀ i, a i ≠ 0) :
    (diagMatrix a).det ≠ 0 := by
  simp [diagMatrix, Matrix.det_diagonal]
  exact Finset.prod_ne_zero (fun i _ => ha i)

/-- The inverse of a diagonal matrix -/
lemma diag_inv (a : Fin n → ℝ) (ha : ∀ i, a i ≠ 0) :
    (diagMatrix a)⁻¹ = diagMatrix (fun i => (a i)⁻¹) := by
  sorry -- Standard diagonal inverse formula

/-- Determinant of diagonal matrix is product of entries -/
lemma det_diag (a : Fin n → ℝ) :
    (diagMatrix a).det = ∏ i, a i := by
  simp [diagMatrix, Matrix.det_diagonal]

/-- The quadratic form 1^T D^{-1} 1 equals sum of reciprocals -/
lemma ones_diag_inv_ones (a : Fin n → ℝ) (ha : ∀ i, a i ≠ 0) :
    Matrix.dotProduct (onesVec n) ((diagMatrix (fun i => (a i)⁻¹)).mulVec (onesVec n)) =
    ∑ i, (a i)⁻¹ := by
  simp [Matrix.dotProduct, Matrix.mulVec, diagMatrix, onesVec, Matrix.diagonal]
  sorry -- Dot product calculation

/-- Main theorem: determinant of rank-one perturbation of diagonal matrix -/
theorem det_rank1_perturbation [DecidableEq (Fin n)] [Fintype (Fin n)]
    (a : Fin n → ℝ) (ha : ∀ i, a i ≠ 0) :
    (matrixA a).det = (1 + ∑ i, (a i)⁻¹) * ∏ i, a i := by
  -- Step 1: A = D + 11^T decomposition (by definition of matrixA)
  unfold matrixA

  -- Step 2: D is invertible since all a_k ≠ 0
  have hD : (diagMatrix a).det ≠ 0 := diag_invertible a ha

  -- Step 3: det(D) = ∏ a_k
  have h_detD : (diagMatrix a).det = ∏ i, a i := det_diag a

  -- Step 4: Apply Matrix Determinant Lemma
  -- det(D + 11^T) = (1 + 1^T D^{-1} 1) det(D)
  have h_lemma : (diagMatrix a + onesMatrix n).det =
      (1 + Matrix.dotProduct (onesVec n) ((diagMatrix a)⁻¹.mulVec (onesVec n))) *
      (diagMatrix a).det := by
    sorry -- Application of matrix_det_lemma

  -- Step 5: 1^T D^{-1} 1 = Σ 1/a_k
  have h_quad : Matrix.dotProduct (onesVec n) ((diagMatrix a)⁻¹.mulVec (onesVec n)) =
      ∑ i, (a i)⁻¹ := by
    rw [diag_inv a ha]
    exact ones_diag_inv_ones a ha

  -- Step 6: Combine
  calc (diagMatrix a + onesMatrix n).det
      = (1 + Matrix.dotProduct (onesVec n) ((diagMatrix a)⁻¹.mulVec (onesVec n))) *
        (diagMatrix a).det := h_lemma
    _ = (1 + ∑ i, (a i)⁻¹) * (diagMatrix a).det := by rw [h_quad]
    _ = (1 + ∑ i, (a i)⁻¹) * ∏ i, a i := by rw [h_detD]
